# Use root/example as user/password credentials
version: "3"
services:
  app:
    build: ./back-end
    ports:
      - "3001:80"
  front-end:
    image: php:apache
    volumes:
      - ./front-end:/var/www/html
    ports:
      - 5000:80
    depends_on:
      - app
